name: 'MC DSFR'
description: 'Installe les modules spécifiques à un site basé sur le DSFR'
type: 'Custom'
recipes:
  - ../recipes/mc_core
install:
  - ui_suite_dsfr
config:
  # Allow config import to continue if config already exists.
  strict: false
  actions:
    system.theme:
      simpleConfigUpdate:
        default: ui_suite_dsfr
