name: 'MC Core'
description: 'Core for both DSFR and native recipe.'
type: 'Custom'
install:
  - admin_toolbar
  - admin_toolbar_tools
  - captcha_captchetat
  - clamav
  - config_split
  - diff
  - easy_breadcrumb
  - eulerian
  - file_browser
  - inline_entity_form
  - lazy
  - linkit
  - matomo
  - metatag
  - minifyhtml
  - module_filter
  - openid_connect
  - paragraphs
  - pathauto
  - purge
  - purge_ui
  - redis
  - s3fs
  - simple_sitemap
  - smtp
  - varnish_purger
  - webform
  - webp
config:
  import:
    config_split:
      - config_split.development_config
      - config_split.staging_config
      - config_split.prod_config
  # Allow config import to continue if config already exists.
  strict: false
